### ISSUE TITLE
issue compiling

### ISSUE THREAD

**Issue by ghost** [GHenkje/Crypter#3]
Program.cs(19,33): error CS0246: The type or namespace name 'Builder' could not be found (are you missing a using
        directive or an assembly reference?)

**Comment by goldgoose1968** [comment]
You have modified the code, I can't find the stubs.

**Comment by GHenkje** [comment]
Hey, thats right the stub will now be compiled by the crypter. The code of the crypter is located in form1.cs
Now you only compile the Crypter. Crypter will compile the stub(and insert the key and encrypted bytes) Hope this helps you.
